title: "Hungtso's Study Journal for Linguistics"
description: "Reading notes, small experiments, and preparation logs."
theme: jekyll-theme-cayman
lang: en
timezone: Asia/Tokyo

header_pages:
  - about.md
