title: "Hungtso's Study Journal for Linguistics"
description: "Reading notes, small experiments, and preparation logs."
url: "https://redleftchen.github.io"
lang: en
timezone: Asia/Tokyo

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

